/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package praktikum9_1402023053;

import javax.swing.*;
import java.text.DecimalFormat;


/**
 *
 * @author Rafli Dika
 */
public class NewJFrame1 extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame1
     */
    public NewJFrame1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        input = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        output = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setText("INPUT");

        input.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        input.setText("jTextField1");
        input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputActionPerformed(evt);
            }
        });

        jLabel2.setText("FROM");

        jLabel3.setText("TO");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "EURO", "IDR", "USD" }));
        jComboBox1.setToolTipText("");
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "EURO", "IDR", "USD" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jLabel4.setText("RESULT");

        output.setText("jTextField2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(input, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(output, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(174, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(input, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(output, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(125, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
        try{
            String str = input.getText();
            double angka = Double.parseDouble(str);

            String kurs1 = jComboBox1.getSelectedItem().toString();
            String kurs2 = jComboBox2.getSelectedItem().toString();
            String result = "";
            
            DecimalFormat df = new DecimalFormat("#.##");


            if(kurs1.equalsIgnoreCase("IDR")){
                if(kurs2.equalsIgnoreCase("USD")){
                    result = "" + df.format(angka / 15670.0) + " $";
                }else if(kurs2.equalsIgnoreCase("EURO")) {
                    result = "" + df.format(angka / 16288.0) + " €";
                }
            }else if(kurs1.equalsIgnoreCase("USD")){
                if(kurs2.equalsIgnoreCase("IDR")){
                    result = "Rp. " + (angka * 15670.0);
                }else if(kurs2.equalsIgnoreCase("EURO")){
                    result = "" + df.format(angka / 1.04) + " €";
                }
            }else if(kurs1.equalsIgnoreCase("EURO")){
                if(kurs2.equalsIgnoreCase("IDR")){
                    result = "Rp. " + (angka * 16288.0);
                }else if(kurs2.equalsIgnoreCase("USD")){
                    result = "" + df.format(angka * 1.04) + " $";
                }
            }

            output.setText(result);
        }
        catch(NumberFormatException nfe){
            JOptionPane.showMessageDialog(this, "Format Bukan Angka", "ERROR MESSAGE", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputActionPerformed
        // TODO add your handling code here:
        try{
            String str = input.getText();
            double angka = Double.parseDouble(str);

            String kurs1 = jComboBox1.getSelectedItem().toString();
            String kurs2 = jComboBox2.getSelectedItem().toString();
            String result = "";
            
            DecimalFormat df = new DecimalFormat("#.##");


            if(kurs1.equalsIgnoreCase("IDR")){
                if(kurs2.equalsIgnoreCase("USD")){
                    result = "" + (angka / 15670.0) + " $";
                }else if(kurs2.equalsIgnoreCase("EURO")) {
                    result = "" + (angka / 16288.0) + " €";
                }
            }else if(kurs1.equalsIgnoreCase("USD")){
                if(kurs2.equalsIgnoreCase("IDR")){
                    result = "Rp. " + (angka * 15670.0);
                }else if(kurs2.equalsIgnoreCase("EURO")){
                    result = "" + df.format(angka / 1.04) + " €";
                }
            }else if(kurs1.equalsIgnoreCase("EURO")){
                if(kurs2.equalsIgnoreCase("IDR")){
                    result = "Rp. " + (angka * 16288.0);
                }else if(kurs2.equalsIgnoreCase("USD")){
                    result = "" + df.format(angka * 1.04) + " $";
                }
            }

            output.setText(result);
        }
        catch(NumberFormatException nfe){
            JOptionPane.showMessageDialog(this, "Format Bukan Angka", "ERROR MESSAGE", JOptionPane.ERROR_MESSAGE);
        }
        
        
    }//GEN-LAST:event_inputActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        
        try{
            String str = input.getText();
            double angka = Double.parseDouble(str);

            String kurs1 = jComboBox1.getSelectedItem().toString();
            String kurs2 = jComboBox2.getSelectedItem().toString();
            String result = "";

            DecimalFormat df = new DecimalFormat("#.##");

            
            if(kurs1.equalsIgnoreCase("IDR")){
                if(kurs2.equalsIgnoreCase("USD")){
                    result = "" + df.format(angka / 15670.0) + " $";
                }else if(kurs2.equalsIgnoreCase("EURO")) {
                    result = "" + (angka / 16288.0) + " €";
                }
            }else if(kurs1.equalsIgnoreCase("USD")){
                if(kurs2.equalsIgnoreCase("IDR")){
                    result = "Rp. " + (angka * 15670.0);
                }else if(kurs2.equalsIgnoreCase("EURO")){
                    result = "" + df.format(angka / 1.04) + " €";
                }
            }else if(kurs1.equalsIgnoreCase("EURO")){
                if(kurs2.equalsIgnoreCase("IDR")){
                    result = "Rp. " + (angka * 16288.0);
                }else if(kurs2.equalsIgnoreCase("USD")){
                    result = "" + df.format(angka * 1.04) + " $";
                }
            }

            output.setText(result);
        }
        catch(NumberFormatException nfe){
            JOptionPane.showMessageDialog(this, "Format Bukan Angka", "ERROR MESSAGE", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new NewJFrame1().setVisible(true);
                
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField input;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField output;
    // End of variables declaration//GEN-END:variables
}
